### PR TITLE
feat: Migrate autocapture elements

### PR DESCRIPTION
**Pull request by tomasfarias**
The PostHog migration tools can be used to migrate from a PostHog instance to another. It works by selecting data from ClickHouse and calling `posthog.capture(...)` with the selected data targeting the new instance.

The problem is that data selection is excluding the `elements_chain` field from ClickHouse. This field is populated for `$autocapture` events with a serialized set of HTML elements that triggered the `$autocapture` event. By not selecting it, we are then not passing it to the call to `posthog.capture`. Thus, when reproducing `$autocapture` events, they are missing all the data for this field.

This is not the only problem: Serializing data to the `elements_chain` field means we have to de-serialize it before passing it to `posthog.capture` as part of the event's `properties`. This logic is implemented in the `plugin-server` [here](https://github.com/PostHog/posthog/blob/master/plugin-server/src/utils/db/elements-chain.ts#L40), and has to be re-implemented in this PR.

### CODE REVIEW

**Comment by xvello** [comment]
Looks OK on a migration from a local instance to prod-US: 

image
image

**Comment by xvello** [comment]
`elements_chain` is now filled, but it does not match what's on the original instance. Screenshot is local devenv & a cloud project after replication:

image

**Comment by fuziontech** [comment]
Hey! Please add a description so the peanut gallery (me) can follow along as to what's going on please!

**Comment by tomasfarias** [comment]
@fuziontech Hey James. We discussed and worked on this issue in Slack, hence the missing description. However, you raise a good point, and we do want to include as many people as we can, so I've added a description. Thank you!

**Comment by fuziontech** [comment]
I appreciate it. For me there's a huge slack <> github disconnect because of timezones so sometimes I'll look at github before catching up on all of slack. It's also super helpful for the future when we go 'why did we do this again?'

**Comment by xvello** [comment]
Pushing a last series of changes that fix the attribute serialization. Text, href, multiple classes work fine the example below, I need to test ID to be exhaustive: 
image

**Pull request merged**
